config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  post "/products/review/create", to:'review_product#create', as:'review_product_creation'
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :spree_reviews, foreign_key: 'spree_product_id',class_name: 'Spree::Review'
  attr_accessor :my_rating

  def i_had_already_voting spree_user_id
    return true unless @my_rating.nil?
    review = Spree::Review.find_by_spree_product_id_and_spree_user_id(id, spree_user_id)
    return nil if review.nil?
    @my_rating = review.rating
    @my_rating
  end
end

app/models/spree/review.rb
class Spree::Review < ApplicationRecord
  belongs_to :spree_product, foreign_key: 'spree_product_id', class_name: "Spree::Product"
  belongs_to :spree_user, foreign_key: 'spree_user_id', class_name: "Spree::User"


  def get_author_name
    spree_user.full_name
  end
end

app/models/spree/review_comment.rb
class Spree::ReviewComment < ApplicationRecord
end

app/controllers/spree/review_product_controller.rb
class Spree::ReviewProductController < Spree::StoreController

  def create
    review = Spree::Review.create review_params
    if review.valid?
      flash[:notice] = "Reseña creada con éxito"
    else
      flash[:error] = "Problemas al crear la reseña"
    end
    product = Spree::Product.find(params[:spree_product_id])
    redirect_to product_path(product.slug)
  end

  private
  def review_params
    params.permit(:body, :rating, :spree_product_id, :spree_user_id)
  end
end

app/views/spree/products/_rating_form.html.erb
<%= form_tag review_product_creation_path, method:'post' do %>
  <%= text_area_tag :body %>
  <%= hidden_field_tag :spree_product_id, product.id %>
  <%= hidden_field_tag :spree_user_id, 1 %>
  <% if product.i_had_already_voting(1) %>
  <%= hidden_field_tag :rating, product.my_rating %>
  <% else %>
  <%= hidden_field_tag :rating %>
  <% end %>
  <div class='starrr' id='rating_star'></div>
  <%= submit_tag :send, value:'Enviar' %>
<% end %>
<script type="text/javascript">
  $('#rating_star').starrr({
    <% if product.i_had_already_voting(1) %>
    readOnly: true,
    rating: <%= product.my_rating %>,
    <% end %>
    change: function(e, value){
      $("input#rating").val(value);
    }
  });
</script>

app/views/spree/products/_reviews.html.erb
<% product.spree_reviews.each do |review| %>
<div class="col-md-12">
  <h2>Escrito por: <%= review.get_author_name %></h2>
  <span><%= review.body %></span>
</div>
<% end %>